### ISSUE TITLE
Screenshots not matching

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/navigation-highlight#1]
Hi @thomasjbradley! I have been working on this assignment for what seems like 100 hours haha. I have all the content in, but can't get the screenshots to match up, specifically on the pages with the images. I'm not sure if it's one big thing I'm missing, or a few smaller things? Any advice would be greatly appreciated!

**Comment by thomasjbradley** [comment]
Let’s start with adjusting the navigation buttons—that might be contributing quite a bit. Two things to change on `.nav a`:

1. Set their `padding` to exactly: `.2em .5em .3em`
2. Add `display: inline-block` otherwise the padding won’t work properly.

**Comment by cmvolden** [comment]
@thomasjbradley Thank you so much! After adding that, and adjusting the img padding, it is now successfully submitted! Much appreciated
